name: Check
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Setup | Install Dependencies
        run: npm ci

      - name: Run | Migrate
        run: |
          npx supabase link --project-ref ${SUPABASE_PROJECT_ID}
          npx supabase db push
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
